name: Output Github Context
on: push

jobs:
  test:
    name: Test Github Context
    runs-on: ubuntu-latest
    steps:
      - name: Getting Github context from this repo
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run : |
          echo "$GITHUB_CONTEXT"
          echo "selesai."
