name: Output Github Context
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch: 
  push:
     branches:
       #- dev
       #- test
       - relase/**
       - asik
env:
  ASIK: ${{ vars.ASIK }}

jobs:
  test:
    name: Test Github Context
    runs-on: ubuntu-latest
    steps:
      - name: Getting Github context from this repo
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run : |
          echo "$GITHUB_CONTEXT"
          echo "------"
          echo "${{ env.GITHUB_CONTEXT }}"
          echo "selesai."

  repository-variables:
    name: repository variables
    runs-on: ubuntu-latest
    steps:
      - name: show variables on repository
        run: |
           echo "${{ env.ASIK }}"

  environment-variables:
    name: environment variables
    runs-on: ubuntu-latest
    environment: ok
    steps:
      - name: show variables on environment
        run: |
          echo "${{ env.ASIK }}"
